newAlcogolMarket/Models/Alcogol/Category/Absent.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace newAlcogolMarket.Models.Alcogol.Category
{
    public class Absent
    {
        [Key]
        public int Id { get; set; } 
        public string Name { get; set; }    
        public string Description { get; set; }
        public ushort price { get;set; }
        public int degree { get; set; } 
        public string country { get; set; }
        [Required]
        public int CategoryId { get; set; }
        [ForeignKey(nameof(CategoryId))]
        public virtual CategoryofAlcogol Category { get; set; }
    }
}

newAlcogolMarket/Models/Alcogol/Category/Beer.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace newAlcogolMarket.Models.Alcogol.Category
{
    public class Beer
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public ushort price { get; set; }
        public int degree { get; set; }
        public string country { get; set; }
        [Required]
        public int CategoryId { get; set; }
        [ForeignKey(nameof(CategoryId))]
        public virtual CategoryofAlcogol Category { get; set; }
    }
}

newAlcogolMarket/Models/Alcogol/Category/Champagne.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace newAlcogolMarket.Models.Alcogol.Category
{
    public class Champagne
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public ushort price { get; set; }
        public int degree { get; set; }
        public string country { get; set; }
        [Required]
        public int CategoryId { get; set; }
        [ForeignKey(nameof(CategoryId))]
        public virtual CategoryofAlcogol Category { get; set; }
    }
}

newAlcogolMarket/Models/Alcogol/Category/Cognac.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace newAlcogolMarket.Models.Alcogol.Category
{
    public class Cognac
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public ushort price { get; set; }
        public int degree { get; set; }
        public string country { get; set; }
        [Required]
        public int CategoryId { get; set; }
        [ForeignKey(nameof(CategoryId))]
        public virtual CategoryofAlcogol Category { get; set; }
    }
}

newAlcogolMarket/Models/Alcogol/Category/Liquor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace newAlcogolMarket.Models.Alcogol.Category
{
    public class Liquor
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public ushort price { get; set; }
        public int degree { get; set; }
        public string country { get; set; }
        [Required]
        public int CategoryId { get; set; }
        [ForeignKey(nameof(CategoryId))]
        public virtual CategoryofAlcogol Category { get; set; }
    }
}

newAlcogolMarket/Models/Alcogol/Category/Vodka.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace newAlcogolMarket.Models.Alcogol.Category
{
    public class Vodka
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public ushort price { get; set; }
        public int degree { get; set; }
        public string country { get; set; }
        [Required]
        public int CategoryId { get; set; }
        [ForeignKey(nameof(CategoryId))]
        public virtual CategoryofAlcogol Category { get; set; }
    }
}

newAlcogolMarket/Models/Alcogol/Category/Whiski.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace newAlcogolMarket.Models.Alcogol.Category
{
    public class Whiski
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public ushort price { get; set; }
        public int degree { get; set; }
        public string country { get; set; }
        [Required]
        public int CategoryId { get; set; }
        [ForeignKey(nameof(CategoryId))]
        public virtual CategoryofAlcogol Category { get; set; }

    }
}

newAlcogolMarket/Models/Alcogol/Category/Wine.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace newAlcogolMarket.Models.Alcogol.Category
{
    public class Wine
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public ushort price { get; set; }
        public int degree { get; set; }
        public string country { get; set; }
        [Required]
        public int CategoryId { get; set; }
        [ForeignKey(nameof(CategoryId))]
        public virtual CategoryofAlcogol Category { get; set; }
    }
}

newAlcogolMarket/Models/Entities/Category.cs
namespace newAlcogolMarket.Models.Entities
{
    public class Category
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }

    }
}

newAlcogolMarket/Models/Entities/Country.cs
namespace newAlcogolMarket.Models.Entities
{
    public class Country
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

newAlcogolMarket/Models/Entities/Product.cs
namespace newAlcogolMarket.Models.Entities
{
    public class Product
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public int CategoryId { get; set; }
        [ForeignKey(nameof(CategoryId))]
        public Category Category { get; set; }
        public int Price { get; set; }
        public int Rating { get; set; }
        public int CountryId { get; set; }
        [ForeignKey(nameof(CountryId))]
        public Country Country { get; set; }
        public double Strenght { get; set; }
        public int SizeId { get; set; }
        [ForeignKey(nameof(SizeId))]
        public Size Size { get; set; }
       

    }
}

newAlcogolMarket/Models/Entities/Size.cs
namespace newAlcogolMarket.Models.Entities
{
    public class Size
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public double Volume { get; set; }
    }
}

newAlcogolMarket/Models/Entities/Snack.cs
namespace newAlcogolMarket.Models.Entities
{
    public class Snack
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public ushort Price { get; set; }
        public ushort Weight { get; set; }
        public string Image { get; set; }
    }
}

newAlcogolMarket/Models/Entities/User.cs
namespace newAlcogolMarket.Models.Entities
{
    public class User
    {
        [Key]
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public List<BasketItem>? BasketItems { get; internal set; }
    }
}

newAlcogolMarket/Models/Entity/Category.cs
namespace newAlcogolMarket.Models.Entity
{   
    public class Category
    
    {   
        [Key]
        public int  Id { get; set; }
        public string Name { get; set; }
    }
}

newAlcogolMarket/Models/Entity/Country.cs
namespace newAlcogolMarket.Models.Entity
{
    public class Country
    {
        public int Id { get; set; } 
        public string Name { get; set; }   
    }
}

newAlcogolMarket/Models/Entity/Product.cs
namespace newAlcogolMarket.Models.Entity
{
    public class Product
    {
        [Key]
        public int Id { get; set; } 
        public string Name { get; set; }
        public ushort Price { get; set; }
        public int CategoryId { get; set; }
        [ForeignKey(nameof(CategoryId))]
        public Category Category { get; set; }
        public int CountryId { get; set; }
        [ForeignKey(nameof(CountryId))]
        public Country Country { get; set; }
        public double Strength { get; set; }
        public int SizeId { get; set; }
        public Size Size { get; set; }
    }
}

newAlcogolMarket/Models/Entity/Size.cs
namespace newAlcogolMarket.Models.Entity
{
    public class Size
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public double Volume { get; set; }

    }
}

newAlcogolMarket/Models/Entity/User.cs
namespace newAlcogolMarket.Models.Entity
{
    public class User
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public List<BasketItem>? BasketItems { get; set; }
    }
}

newAlcogolMarket/Models/ProductViewModel.cs
using newAlcogolMarket.Models.Entities;

namespace newAlcogolMarket.Models
{
    public class ProductViewModel
    {
        public int Amount { get; set; }
        public Product Product { get; set; }
    }
}

newAlcogolMarket/Controllers/BasketItemController.cs
using Microsoft.AspNetCore.Mvc;
using newAlcogolMarket.Manager.BasketItems;
using newAlcogolMarket.Manager.Products;
using newAlcogolMarket.Models.Entities;

namespace newAlcogolMarket.Controllers
{
    public class BasketItemController : Controller
    {

        private readonly IBasketItemManager _manager;
        private readonly IProductManager _productManager;
        public BasketItemController(IBasketItemManager manager, IProductManager productManager)
        {
            _manager = manager;
            _productManager = productManager;
        }
        public async Task<IActionResult> Add(int productId, int quantity)
        {
           var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
                return RedirectToAction("SignIn","User");
            while(quantity > 0)
            {
                var item = new BasketItem
                {
                    ProductId = productId,
                    Quantity = quantity,
                    UserId = (int)userId,
                    DateCreated = DateTime.Now,
                    Price = _productManager.Get(productId).Price
                };
                await _manager.Create(item);
                quantity--;
            }
            
            return Redirect("/Product/Details/" + productId);
        }
        public async Task<IActionResult> Delete(int Id)
        {
            await _manager.Delete(Id);
            return RedirectToAction("Basket", "User");
        }
        public async Task<IActionResult> Pay()
        {
            await _manager.Clear();
            return RedirectToAction("Thanks","User");

        }
    }
}

newAlcogolMarket/Views/User/AdminPanel.cshtml
@{
    ViewData["Title"] = "Admin Panel";
}
<!DOCTYPE html>
<html lang="ru">
<head>
    <link rel="stylesheet" href="~/css/admin.css" asp-append-version="true" />
</head>
<body>
<div class="head">
    <h1>Админ страничка</h1>
</div>
<div class="somecontainer">
    <nav class="leftmenu">
        <a asp-action="ProductView">Products</a><br />
        <a asp-action="CategoryView">Categories</a><br />
        <a asp-action="UserView">Users</a><br />
        <a asp-action="SnackView">Snacks</a><br/>
        <a asp-action="SizeView">Sizes</a><br/>
        <a asp-action="CountryView">Countries</a><br/>
    </nav>
</div>
<div>
    <form method="post" asp-action="SignOut" asp-controller="User">
    <button>Выход</button>
    </form>
</div>
</body>
</html>

newAlcogolMarket/Views/User/Basket.cshtml
@model List<BasketItem>
<head>
	<meta charset="utf-8">
        <link href="site.css" rel="stylesheet">
        <style>
        .basket{
            text-align: center;
        }
        </style>
        <title>BEDOLAGI-Корзина</title>
</head>
<body>
	<audio src="https://d9olupt5igjta.cloudfront.net/samples/sample_files/21999/a97133c8b3525c510265dc77272fd5874da7337a/mp3/_Impact_2.mp3?1540417944" autoplay></audio>
    <p class="basket">Список покупок:</p>
	<div>
		<table>
		@foreach(var item in Model)
		{
			<div class="text1">
		<a>
			@item.Product.Name
		</a></div>
		<div class="text2"><a>
			@item.Product.Price
		</a></div>
		<div class="text3">
			<form asp-action="Delete" asp-controller="BasketItem" asp-route-Id=@item.Id>
		<button>Удалить</button>
		</form>
		</div>
		<br>
		}
		</table>
	</div>
	<a>@ViewBag.TotalAmount</a>
	<form asp-action="Pay" asp-controller="BasketItem">
	<input type="submit" value="Оплатить"/>
	</form>
</body>

newAlcogolMarket/Views/User/CategoryView.cshtml
@model List<Category>
<head>
    <link rel="stylesheet" href="~/css/admin.css"/>
</head>
<body>
<h3>Добавить Category</h3>
<form asp-action="AddCategory" style="display:flex;">
    <p>
        <label>Name</label><br />
        <input type="text" name="Name" />
    </p>
    <input type="submit" value="Добавить" />
</form>
<br />
<div class="somecontainer">
    <nav class="leftmenu">
        <a asp-action="ProductView">Products</a><br />
        <a asp-action="CategoryView">Categories</a><br />
        <a asp-action="UserView">Users</a><br />
        <a asp-action="SnackView">Snacks</a><br/>
        <a asp-action="SizeView">Sizes</a><br/>
        <a asp-action="CountryView">Countries</a><br/>
    </nav>
</div>
<div>
        <table>
            <tr>
                <td>Id</td>
                <td>Name</td>
            </tr>
        </table>
    @foreach(var item in Model)
    {
        <table>   
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td style="position: relative;box-sizing: border-box; top: 0px;">
                <form asp-controller="User" asp-action="DeleteCategory" method="post" asp-route-id="@item.Id" style="display:flex;">
                    <input type="submit" value="Удалить">
                </form>
                <form asp-controller="User" asp-action="UpdateCategory" method="post" asp-route-id="@item.Id" style="display:flex;">
                    <p>
                        <label>Name</label><br/>
                        <input type="text" name="Name" />
                    </p>
                    <input type="submit" value="Сохранить" />
                </form>
            </td>
        </tr>
        </table>
    }
</div>
</body>

newAlcogolMarket/Views/User/CountryView.cshtml
@model List<Country>
<head>
    <link rel="stylesheet" href="~/css/admin.css"/>
</head>
<h3>Добавить Country</h3>
<form asp-action="AddCountry" style="display:flex;">
    <p>
        <label>Name</label><br />
        <input type="text" name="Name" />
    </p>
    <input type="submit" value="Добавить" />
</form>
<br />
<div class="somecontainer">
    <nav class="leftmenu">
        <a asp-action="ProductView">Products</a><br />
        <a asp-action="CategoryView">Categories</a><br />
        <a asp-action="UserView">Users</a><br />
        <a asp-action="SnackView">Snacks</a><br/>
        <a asp-action="SizeView">Sizes</a><br/>
        <a asp-action="CountryView">Countries</a><br/>
    </nav>
</div>
<div>
        <table>
            <tr>
                <td>Id</td>
                <td>Name</td>
            </tr>
        </table>
    @foreach(var item in Model)
    {
        <table>   
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td style="position: relative;box-sizing: border-box; top: 0px;">
                <form asp-controller="User" asp-action="DeleteCountry" method="post" asp-route-id="@item.Id" style="display:flex;">
                    <input type="submit" value="Удалить">
                </form>
                <form asp-controller="User" asp-action="UpdateCountry" method="post" asp-route-id="@item.Id" style="display:flex;">
                    <p>
                        <label>Name</label><br/>
                        <input type="text" name="Name" />
                    </p>
                    <input type="submit" value="Сохранить" />
                </form>
            </td>
        </tr>
        </table>
    }
</div>

newAlcogolMarket/Views/User/Entities.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
        <meta charset="utf-8">
        <link href="site.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/adm.css" asp-append-version="true" />
</head>
<body>
<div class="head">
    <h1>Админ страничка</h1>
</div>
<div class="somecontainer">
    <nav class="leftmenu">
        <a asp-action="ProductView">Products</a><br />
        <a asp-action="CategoryView">Categories</a><br />
        <a asp-action="UserView">Users</a><br />
        <a asp-action="SnackView">Snacks</a><br/>
        <a asp-action="SizeView">Sizes</a><br/>
        <a asp-action="CountryView">Countries</a><br/>
    </nav>
</div>
</body>

newAlcogolMarket/Views/User/Login.cshtml
<html>
    <head>
        <meta charset='utf-8' />
    </head>
    <body>
        <h2>Login Form</h2>
        <form method='post'>
            <p>
                <label>Login</label><br />
                <input name='login' />
            </p>
            <p>
                <label>Password</label><br />
                <input type='password' name='password' />
            </p>
            <input  asp-action="SignUp" type='submit' value='Login' />
        </form>
    </body>
</html>

newAlcogolMarket/Views/User/ProductView.cshtml
@model List<Product>
<head>
    <link rel="stylesheet" href="~/css/admin.css"/>
</head>
<body>
<h3>Добавить Product</h3>
<form asp-action="AddProduct" asp-controller="User" style="display:flex;">
    <p>
        <label>Name</label><br />
        <input type="text" name="Name" />
    </p>
    <p>
        <label>Price</label><br />
        <input type="text" name="Price" />
    </p>
    <p>
        <label>Rating</label><br />
        <input type="text" name="Rating" />
    </p>
    <p>
        <label>Category</label><br />
        <input type="text" name="CategoryId" />
    </p>
    <p>
        <label>Size</label><br />
        <input type="text" name="SizeId" />
    </p>
    <p>
        <label>Strenght</label><br />
        <input type="text" name="Strenght" />
    </p>
    <p>
        <label>Country</label><br />
        <input type="text" name="CountryId" />
    </p>
     <p>
        <label>Image</label><br />
        <input type="text" name="Image" />
    </p>
    <input type="submit" value="Добавить" />
</form>
<div class="somecontainer">
    <nav class="leftmenu">
        <a asp-action="ProductView">Products</a><br />
        <a asp-action="CategoryView">Categories</a><br />
        <a asp-action="UserView">Users</a><br />
        <a asp-action="SnackView">Snacks</a><br/>
        <a asp-action="SizeView">Sizes</a><br/>
        <a asp-action="CountryView">Countries</a><br/>
    </nav>
</div>
<br />
@*<h3>Поиск по:</h3>
<form asp-action="Milks" method="post" style="display:flex;">
    <p>
        <label>Name</label><br />
        <input type="text" name="name" />
    </p>
    <input type="submit" value="Фильтр" />
</form>*@
        <table>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Price</th>
                <th>Rating</th>
                <th>Category</th>
                <th>Size</th>
                <th>Strenght</th>
                <th>Country</th>
                <th>Image</th>
                <th></th>
            </tr>
        </table>
@foreach(var item in Model)
    {
        <table style="text-align:center"> 
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.Price</td>
            <td>@item.Rating</td>
            <td>@item.Category.Name</td>
            <td>@item.Size.Volume</td>
            <td>@item.Strenght</td>
            <td>@item.Country.Name</td>
            <td>@item.Image</td>
            <td style="position: relative;box-sizing: border-box;left:250; top: 0px;">
                <form asp-controller="User" asp-action="DeleteProduct" method="post" asp-route-id="@item.Id" style="display:flex;">
                    <input type="submit" value="Удалить">
                </form>
                <form asp-controller="User" asp-action="UpdateProduct" method="post" asp-route-id="@item.Id" style="display:flex;">
                    <p>
                        <label>Name</label><br/>
                        <input type="text" name="Name" />
                    </p>
                    <p>
                        <label>Price</label><br />
                         <input type="text" name="Price" />
                    </p>
                    <p>
                        <label>Raiting</label><br />
                         <input type="text" name="Raiting" />
                    </p>
                    <p>
                        <label>Category</label><br />
                         <input type="text" name="CategoryId" />
                    </p>
                    <p>
                        <label>Size</label><br />
                         <input type="text" name="SizeId" />
                    </p>
                    <p>
                        <label>Strenght</label><br />
                         <input type="text" name="Strenght" />
                    </p>
                    <p>
                        <label>Country</label><br />
                         <input type="text" name="CountryId" />
                    </p>
                        <input type="submit" value="Сохранить" />
                </form>
            </td>
        </tr>
        </table>
    }
</body>

newAlcogolMarket/Views/User/Register.cshtml
@{
    ViewData["Title"] = "Регистрация";
}
<html>
    <head>
        <meta charset='utf-8' />
    </head>
    <body>
        <h2>Регистрация</h2>
        <div id="block-search">
        <form method='post'>
            <p>
                <label>Login</label><br/>
                <input name='login' />
            </p>
            <p>
                <label>Password</label><br />
                <font ><input type='password' name='password' /></font>
            </p>
            <input asp-action="Register" type='submit' value='Зарегистрироваться'/>
        </form>
        </div>
    </body>
</html>

newAlcogolMarket/Views/User/SignIn.cshtml
<html>
    <head>
        <meta charset='utf-8' />
    </head>
    <body>
        <h2>Вход</h2>
        <form method="post">
            <p>
                <label>Login</label><br/>
                <input name='login' />
            </p>
            <p>
                <label>Password</label><br />
                <input type='password' name='password' />
            </p>
            </br>
            
            <input  asp-action="SignIn" type='submit' value='Войти' />
        </form>
        <form>
        <input  asp-action="Register" type='submit' value='Регистрация' />
        </form>
    </body>
</html>

newAlcogolMarket/Views/User/SizeView.cshtml
@model List<Size>
<head>
    <link rel="stylesheet" href="~/css/admin.css"/>
</head>
<h3>Добавить Size</h3>
<form asp-action="AddSize" style="display:flex;">
    <p>
        <label>Name</label><br />
        <input type="text" name="Name" />
    </p>
    <p>
        <label>Volume</label><br />
        <input type="text" name="Volume" />
    </p>
    <input type="submit" value="Добавить" />
</form>
<div class="somecontainer">
    <nav class="leftmenu">
        <a asp-action="ProductView">Products</a><br />
        <a asp-action="CategoryView">Categories</a><br />
        <a asp-action="UserView">Users</a><br />
        <a asp-action="SnackView">Snacks</a><br/>
        <a asp-action="SizeView">Sizes</a><br/>
        <a asp-action="CountryView">Countries</a><br/>
    </nav>
</div>
<br />
<div>
        <table>
            <tr>
                <td>Id</td>
                <td>Name</td>
                <td>Volume</td>
            </tr>
        </table>
    @foreach(var item in Model)
    {
        <table>
            
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.Volume</td>
            <td style="position: relative;box-sizing: border-box;top: 0px;">
                <form asp-controller="User" asp-action="DeleteSize" method="post" asp-route-id="@item.Id" style="display:flex;">
                    <input type="submit" value="Удалить">
                </form>
                <form asp-controller="User" asp-action="UpdateSize" method="post" asp-route-id="@item.Id" style="display:flex;">
                    <p>
                        <label>Name</label><br/>
                        <input type="text" name="Name" />
                    </p>
                    <p>
                        <label>Volume</label><br/>
                         <input type="text" name="Volume" />
                    </p>
                    <input type="submit" value="Сохранить" />
                </form>
            </td>
        </tr>
        </table>
    }
</div>

newAlcogolMarket/Views/User/SnackView.cshtml
@model List<Snack>
<head>
    <link rel="stylesheet" href="~/css/admin.css"/>
</head>
<h3>Добавить Snack</h3>
<form asp-action="AddSnack" style="display:flex;">
    <p>
        <label>Name</label><br />
        <input type="text" name="Name" />
    </p>
    <p>
        <label>Price</label><br />
        <input type="text" name="Price" />
    </p>
    <p>
        <label>Weight</label><br />
        <input type="text" name="Weight" />
    </p>
    <p>
        <label>Image</label><br />
        <input type="text" name="Image" />
    </p>
    <input type="submit" value="Добавить" />
</form>
<div class="somecontainer">
    <nav class="leftmenu">
        <a asp-action="ProductView">Products</a><br />
        <a asp-action="CategoryView">Categories</a><br />
        <a asp-action="UserView">Users</a><br />
        <a asp-action="SnackView">Snacks</a><br/>
        <a asp-action="SizeView">Sizes</a><br/>
        <a asp-action="CountryView">Countries</a><br/>
    </nav>
</div>
<br />
<div>
        <table>
            <tr>
                <td>Id</td>
                <td>Name</td>
                <td>Price</td>
                <td>Weight</td>
                <td>Image</td>
            </tr>
        </table>
    @foreach(var item in Model)
    {
        <table>
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.Price</td>
            <td>@item.Weight</td>
            <td>@item.Image</td>
            <td style="position: relative;box-sizing: border-box; top: 0px;">
                <form asp-controller="User" asp-action="DeleteProduct" method="post" asp-route-id="@item.Id" style="display:flex;">
                    <input type="submit" value="Удалить">
                </form>
                <form asp-controller="User" asp-action="UpdateProduct" method="post" asp-route-id="@item.Id" style="display:flex;">
                    <p>
                        <label>Name</label><br/>
                        <input type="text" name="Name" />
                    </p>
                    <p>
                        <label>Price</label><br />
                         <input type="text" name="Price" />
                    </p>
                    <p>
                        <label>Weight</label><br />
                         <input type="text" name="Weight" />
                    </p>
                    <p>
                        <label>Image</label><br />
                         <input type="text" name="Image" />
                    </p>
                   <input type="submit" value="Сохранить" />
                </form>
            </td>
        </tr>
        </table>
    }
</div>

newAlcogolMarket/Views/User/Thanks.cshtml
@{
    ViewData["Title"] = "Admin Panel";
}
<!DOCTYPE html>
<html lang="ru">
<head>
    <link rel="stylesheet" href="~/css/admin.css" asp-append-version="true" />
</head>
<body>
    <h1>THANKS</h1>
</body>

newAlcogolMarket/Views/User/UserPanel.cshtml
@{
    ViewData["Title"] = "User Panel";
}
<!DOCTYPE html>
<html lang="ru">
<head>
    <link rel="stylesheet" href="~/css/admin.css" asp-append-version="true" />
</head>
<body>
    <h1>
        User Panel
    </h1>
</body>

newAlcogolMarket/Views/User/UserView.cshtml
@model List<User>
<head>
    <link rel="stylesheet" href="~/css/admin.css"/>
</head>
<h3>Добавить User</h3>
<form asp-action="AddUser" style="display:flex;">
    <p>
        <label>Login</label><br />
        <input type="text" name="Login" />
    </p>
    <p>
        <label>Password</label><br />
        <input type="text" name="Password" />
    </p>
    <input type="submit" value="Добавить" />
</form>
<div class="somecontainer">
    <nav class="leftmenu">
        <a asp-action="ProductView">Products</a><br />
        <a asp-action="CategoryView">Categories</a><br />
        <a asp-action="UserView">Users</a><br />
        <a asp-action="SnackView">Snacks</a><br/>
        <a asp-action="SizeView">Sizes</a><br/>
        <a asp-action="CountryView">Countries</a><br/>
    </nav>
</div>
<br/>
<div>
        <table>
            <tr>
                <td>Id</td>
                <td>Login</td>
                <td>Password</td>
            </tr>
        </table>
    @foreach(var item in Model)
    {
        <table>
        <tr>
            <td>@item.Id</td>
            <td>@item.Login</td>
            <td>@item.Password</td>
             <td style="position: relative;box-sizing: border-box; top: 0px;">
                <form asp-controller="User" asp-action="DeleteUser" method="post" asp-route-id="@item.Id" style="display:flex;">
                    <input type="submit" value="Удалить">
                </form>
                <form asp-controller="User" asp-action="UpdateUser" method="post" asp-route-id="@item.Id" style="display:flex;">
                    <p>
                        <label>Login</label><br/>
                        <input type="text" name="Login" />
                    </p>
                    <p>
                        <label>Password</label><br />
                         <input type="text" name="Password" />
                    </p>
                   <input type="submit" value="Сохранить" />
                </form>
            </td>
        </tr>
        </table>
    }
</div>